### ISSUE TITLE
Bootstrap outdated

### ISSUE THREAD

**Issue by ripexz** [Teamwork/node-webkit-base-app#3]
Same issue as the hipster-seed: https://github.com/Anonyfox/node-webkit-hipster-seed/issues/10

Since this is our own thing we ought to take care of that. The unofficial bootstrap-less package is using 2.3.2 and Bootstrap 3 has been out for a while.

Even if we're not adding an official dependency (we don't have one now) at least we could manually update the bootstrap LESS files.

**Comment by adam-lynch** [comment]
Huh, I thought we used the latest version. I must've just used whatever came with hipster-seed. I guess we'll have to manually update it. I don't think Bootstrap is like your typical dependency (i.e. like any managed by Bower). It should be modified and built on top of (with any needless modules removed).
